---
name: Mail on Push

on:
  push:
    branches:
      - main

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Email on Push
        uses: dawidd6/action-send-mail@v1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Repository Push Notification"
          to: "jyri.vaitmaa@tthk.ee"
          from: "marcus.villems@gmail.com"
          body: |
            Repository: ${{github.repository}}
            Committer: ${{github.event.pusher.name}}
            Commit Message: ${{github.event.head_commit.message}}
            test
